# Needed secrets for this workflow:
# DOCKER_USERNAME
# DOCKER_PASSWORD
name: build-and-push-images
on:
  push:
    branches:
      - main
jobs:
  build_and_push:
    name: Build Docker images and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        ## Used for Multi-Arch Builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build And Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/${{ github.event.repository.name }}:latest
          platforms: linux/amd64,linux/arm64
